import HeroPage from "@/app/components/Hero/page"
import Revolutionalize from "@/app/components/Revolutionalize";
import FAQs from "@/app/components/FAQs";
import { Metadata } from "next";
import BentoGallery from "@/app/components/ui/Bentogallery";
import ScrollTextReveal from "@/app/components/ui/ScrollTextReveal";
import Brands from "@/app/components/ui/Brands"

// export const metadata: Metadata = {
//   title: "Ken Williams",
//   description: "Generated by create next app",
// };

export default function Page() {
  return (
    <div className="overflow-x-hidden bg-black">
      <HeroPage />
      <Revolutionalize />
      <Brands />
      <BentoGallery />
      <ScrollTextReveal />
      <FAQs />
    </div>
  );
}
