import Image from "next/image";
import Footer from "./Footer/page"
import HeroPage from "./Hero/page"
import Revolutionalize from "./components/Revolutionalize";
import FAQs from "./components/FAQs";
import { Metadata } from "next";
import BentoGallery from "./components/ui/Bentogallery";

export const metadata: Metadata = {
  title: "Ken Williams",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <HeroPage />
      <Revolutionalize />
      <BentoGallery />
      <FAQs />
    </div>
  );
}
