import Image from "next/image";
import Footer from "./components/Footer/page"
import HeroPage from "./components/Hero/page"
import Revolutionalize from "./components/Revolutionalize";
import FAQs from "./components/FAQs";
import { Metadata } from "next";
import BentoGallery from "./components/ui/Bentogallery";
// import VideoShowcase from "./components/VideoShowcase";
import ScrollTextReveal from "./components/ui/ScrollTextReveal";

export const metadata: Metadata = {
  title: "Ken Williams",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className="overflow-x-hidden bg-black">
      <HeroPage />
      <Revolutionalize />
      <BentoGallery />
      <ScrollTextReveal />
      <FAQs />
    </div>
  );
}
