import type { Metadata } from "next";
import Home from "@/app/Home/page"

export const metadata: Metadata = {
  title: "Ken Williams",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <Home />
  );
}